# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!

target 'Lighthouse' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lighthouse
    pod 'RxSwift', '4.3.1'
    pod 'RxCocoa', '4.3.1'
    
    pod 'SnapKit', '5.0.1'

    pod 'MaterialComponents/BottomSheet', '101.1.1'
    pod 'MaterialComponents/schemes/Shape', '101.1.1'



  target 'LighthouseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LighthouseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
